#include "headers.h"
#include "vertexFormats.h"

char const* POSITION = "POSITION";
char const* TEXCOORD = "TEXCOORD";

D3D12_INPUT_ELEMENT_DESC const STextVertexFormat::desc[] = 
{
	{ POSITION, 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 },
	{ TEXCOORD, 0, DXGI_FORMAT_R32G32_FLOAT, 0, D3D12_APPEND_ALIGNED_ELEMENT, D3D12_INPUT_CLASSIFICATION_PER_VERTEX_DATA, 0 }
};